[package]
name = "sgutils"
version = "0.0.1"
license = "MIT"
authors = ["Richard Bradfield <bradfier@fstab.me>"]
description = """
Bindings for libsgutils2 for interacting with SCSI-Generic
device drivers under Linux.

Placeholder crate.
"""

[dependencies.libsgutils2-sys]
path = "libsgutils2-sys"
