/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct sg_simple_inquiry_resp {
    pub peripheral_qualifier: ::std::os::raw::c_uchar,
    pub peripheral_type: ::std::os::raw::c_uchar,
    pub byte_1: ::std::os::raw::c_uchar,
    pub version: ::std::os::raw::c_uchar,
    pub byte_3: ::std::os::raw::c_uchar,
    pub byte_5: ::std::os::raw::c_uchar,
    pub byte_6: ::std::os::raw::c_uchar,
    pub byte_7: ::std::os::raw::c_uchar,
    pub vendor: [::std::os::raw::c_char; 9usize],
    pub product: [::std::os::raw::c_char; 17usize],
    pub revision: [::std::os::raw::c_char; 5usize],
}
impl ::std::default::Default for sg_simple_inquiry_resp {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub enum sg_pt_base { }
extern "C" {
    pub fn sg_ll_inquiry(sg_fd: ::std::os::raw::c_int,
                         cmddt: ::std::os::raw::c_int,
                         evpd: ::std::os::raw::c_int,
                         pg_op: ::std::os::raw::c_int,
                         resp: *mut ::std::os::raw::c_void,
                         mx_resp_len: ::std::os::raw::c_int,
                         noisy: ::std::os::raw::c_int,
                         verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_log_select(sg_fd: ::std::os::raw::c_int,
                            pcr: ::std::os::raw::c_int,
                            sp: ::std::os::raw::c_int,
                            pc: ::std::os::raw::c_int,
                            pg_code: ::std::os::raw::c_int,
                            subpg_code: ::std::os::raw::c_int,
                            paramp: *mut ::std::os::raw::c_uchar,
                            param_len: ::std::os::raw::c_int,
                            noisy: ::std::os::raw::c_int,
                            verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_log_sense(sg_fd: ::std::os::raw::c_int,
                           ppc: ::std::os::raw::c_int,
                           sp: ::std::os::raw::c_int,
                           pc: ::std::os::raw::c_int,
                           pg_code: ::std::os::raw::c_int,
                           subpg_code: ::std::os::raw::c_int,
                           paramp: ::std::os::raw::c_int,
                           resp: *mut ::std::os::raw::c_uchar,
                           mx_resp_len: ::std::os::raw::c_int,
                           noisy: ::std::os::raw::c_int,
                           verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_mode_select6(sg_fd: ::std::os::raw::c_int,
                              pf: ::std::os::raw::c_int,
                              sp: ::std::os::raw::c_int,
                              paramp: *mut ::std::os::raw::c_void,
                              param_len: ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_mode_select10(sg_fd: ::std::os::raw::c_int,
                               pf: ::std::os::raw::c_int,
                               sp: ::std::os::raw::c_int,
                               paramp: *mut ::std::os::raw::c_void,
                               param_len: ::std::os::raw::c_int,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_mode_sense6(sg_fd: ::std::os::raw::c_int,
                             dbd: ::std::os::raw::c_int,
                             pc: ::std::os::raw::c_int,
                             pg_code: ::std::os::raw::c_int,
                             sub_pg_code: ::std::os::raw::c_int,
                             resp: *mut ::std::os::raw::c_void,
                             mx_resp_len: ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_mode_sense10(sg_fd: ::std::os::raw::c_int,
                              llbaa: ::std::os::raw::c_int,
                              dbd: ::std::os::raw::c_int,
                              pc: ::std::os::raw::c_int,
                              pg_code: ::std::os::raw::c_int,
                              sub_pg_code: ::std::os::raw::c_int,
                              resp: *mut ::std::os::raw::c_void,
                              mx_resp_len: ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_prevent_allow(sg_fd: ::std::os::raw::c_int,
                               prevent: ::std::os::raw::c_int,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_readcap_10(sg_fd: ::std::os::raw::c_int,
                            pmi: ::std::os::raw::c_int,
                            lba: ::std::os::raw::c_uint,
                            resp: *mut ::std::os::raw::c_void,
                            mx_resp_len: ::std::os::raw::c_int,
                            noisy: ::std::os::raw::c_int,
                            verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_readcap_16(sg_fd: ::std::os::raw::c_int,
                            pmi: ::std::os::raw::c_int, llba: uint64_t,
                            resp: *mut ::std::os::raw::c_void,
                            mx_resp_len: ::std::os::raw::c_int,
                            noisy: ::std::os::raw::c_int,
                            verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_report_luns(sg_fd: ::std::os::raw::c_int,
                             select_report: ::std::os::raw::c_int,
                             resp: *mut ::std::os::raw::c_void,
                             mx_resp_len: ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_request_sense(sg_fd: ::std::os::raw::c_int,
                               desc: ::std::os::raw::c_int,
                               resp: *mut ::std::os::raw::c_void,
                               mx_resp_len: ::std::os::raw::c_int,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_start_stop_unit(sg_fd: ::std::os::raw::c_int,
                                 immed: ::std::os::raw::c_int,
                                 pc_mod__fl_num: ::std::os::raw::c_int,
                                 power_cond: ::std::os::raw::c_int,
                                 noflush__fl: ::std::os::raw::c_int,
                                 loej: ::std::os::raw::c_int,
                                 start: ::std::os::raw::c_int,
                                 noisy: ::std::os::raw::c_int,
                                 verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_sync_cache_10(sg_fd: ::std::os::raw::c_int,
                               sync_nv: ::std::os::raw::c_int,
                               immed: ::std::os::raw::c_int,
                               group: ::std::os::raw::c_int,
                               lba: ::std::os::raw::c_uint,
                               count: ::std::os::raw::c_uint,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_test_unit_ready(sg_fd: ::std::os::raw::c_int,
                                 pack_id: ::std::os::raw::c_int,
                                 noisy: ::std::os::raw::c_int,
                                 verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_test_unit_ready_progress(sg_fd: ::std::os::raw::c_int,
                                          pack_id: ::std::os::raw::c_int,
                                          progress:
                                              *mut ::std::os::raw::c_int,
                                          noisy: ::std::os::raw::c_int,
                                          verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_simple_inquiry(sg_fd: ::std::os::raw::c_int,
                             inq_data: *mut sg_simple_inquiry_resp,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_mode_page_offset(resp: *const ::std::os::raw::c_uchar,
                               resp_len: ::std::os::raw::c_int,
                               mode_sense_6: ::std::os::raw::c_int,
                               err_buff: *mut ::std::os::raw::c_char,
                               err_buff_len: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_get_mode_page_controls(sg_fd: ::std::os::raw::c_int,
                                     mode6: ::std::os::raw::c_int,
                                     pg_code: ::std::os::raw::c_int,
                                     sub_pg_code: ::std::os::raw::c_int,
                                     dbd: ::std::os::raw::c_int,
                                     flexible: ::std::os::raw::c_int,
                                     mx_mpage_len: ::std::os::raw::c_int,
                                     success_mask: *mut ::std::os::raw::c_int,
                                     pcontrol_arr:
                                         *mut *mut ::std::os::raw::c_void,
                                     reported_len: *mut ::std::os::raw::c_int,
                                     verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_cmds_open_device(device_name: *const ::std::os::raw::c_char,
                               read_only: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_cmds_open_flags(device_name: *const ::std::os::raw::c_char,
                              flags: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_cmds_close_device(device_fd: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_cmds_version() -> *const ::std::os::raw::c_char;
    pub fn sg_cmds_process_resp(ptvp: *mut sg_pt_base,
                                leadin: *const ::std::os::raw::c_char,
                                pt_res: ::std::os::raw::c_int,
                                mx_di_len: ::std::os::raw::c_int,
                                sense_b: *const ::std::os::raw::c_uchar,
                                noisy: ::std::os::raw::c_int,
                                verbose: ::std::os::raw::c_int,
                                o_sense_cat: *mut ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_ata_pt(sg_fd: ::std::os::raw::c_int,
                        cdbp: *const ::std::os::raw::c_uchar,
                        cdb_len: ::std::os::raw::c_int,
                        timeout_secs: ::std::os::raw::c_int,
                        dinp: *mut ::std::os::raw::c_void,
                        doutp: *mut ::std::os::raw::c_void,
                        dlen: ::std::os::raw::c_int,
                        sensep: *mut ::std::os::raw::c_uchar,
                        max_sense_len: ::std::os::raw::c_int,
                        ata_return_dp: *mut ::std::os::raw::c_uchar,
                        max_ata_return_len: ::std::os::raw::c_int,
                        residp: *mut ::std::os::raw::c_int,
                        verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_format_unit(sg_fd: ::std::os::raw::c_int,
                             fmtpinfo: ::std::os::raw::c_int,
                             longlist: ::std::os::raw::c_int,
                             fmtdata: ::std::os::raw::c_int,
                             cmplist: ::std::os::raw::c_int,
                             dlist_format: ::std::os::raw::c_int,
                             timeout_secs: ::std::os::raw::c_int,
                             paramp: *mut ::std::os::raw::c_void,
                             param_len: ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_get_lba_status(sg_fd: ::std::os::raw::c_int,
                                start_llba: uint64_t,
                                resp: *mut ::std::os::raw::c_void,
                                alloc_len: ::std::os::raw::c_int,
                                noisy: ::std::os::raw::c_int,
                                verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_persistent_reserve_in(sg_fd: ::std::os::raw::c_int,
                                       rq_servact: ::std::os::raw::c_int,
                                       resp: *mut ::std::os::raw::c_void,
                                       mx_resp_len: ::std::os::raw::c_int,
                                       noisy: ::std::os::raw::c_int,
                                       verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_persistent_reserve_out(sg_fd: ::std::os::raw::c_int,
                                        rq_servact: ::std::os::raw::c_int,
                                        rq_scope: ::std::os::raw::c_int,
                                        rq_type: ::std::os::raw::c_uint,
                                        paramp: *mut ::std::os::raw::c_void,
                                        param_len: ::std::os::raw::c_int,
                                        noisy: ::std::os::raw::c_int,
                                        verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_read_block_limits(sg_fd: ::std::os::raw::c_int,
                                   resp: *mut ::std::os::raw::c_void,
                                   mx_resp_len: ::std::os::raw::c_int,
                                   noisy: ::std::os::raw::c_int,
                                   verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_read_buffer(sg_fd: ::std::os::raw::c_int,
                             mode: ::std::os::raw::c_int,
                             buffer_id: ::std::os::raw::c_int,
                             buffer_offset: ::std::os::raw::c_int,
                             resp: *mut ::std::os::raw::c_void,
                             mx_resp_len: ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_read_defect10(sg_fd: ::std::os::raw::c_int,
                               req_plist: ::std::os::raw::c_int,
                               req_glist: ::std::os::raw::c_int,
                               dl_format: ::std::os::raw::c_int,
                               resp: *mut ::std::os::raw::c_void,
                               mx_resp_len: ::std::os::raw::c_int,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_read_long10(sg_fd: ::std::os::raw::c_int,
                             pblock: ::std::os::raw::c_int,
                             correct: ::std::os::raw::c_int,
                             lba: ::std::os::raw::c_uint,
                             resp: *mut ::std::os::raw::c_void,
                             xfer_len: ::std::os::raw::c_int,
                             offsetp: *mut ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_read_long16(sg_fd: ::std::os::raw::c_int,
                             pblock: ::std::os::raw::c_int,
                             correct: ::std::os::raw::c_int, llba: uint64_t,
                             resp: *mut ::std::os::raw::c_void,
                             xfer_len: ::std::os::raw::c_int,
                             offsetp: *mut ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_read_media_serial_num(sg_fd: ::std::os::raw::c_int,
                                       resp: *mut ::std::os::raw::c_void,
                                       mx_resp_len: ::std::os::raw::c_int,
                                       noisy: ::std::os::raw::c_int,
                                       verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_reassign_blocks(sg_fd: ::std::os::raw::c_int,
                                 longlba: ::std::os::raw::c_int,
                                 longlist: ::std::os::raw::c_int,
                                 paramp: *mut ::std::os::raw::c_void,
                                 param_len: ::std::os::raw::c_int,
                                 noisy: ::std::os::raw::c_int,
                                 verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_receive_diag(sg_fd: ::std::os::raw::c_int,
                              pcv: ::std::os::raw::c_int,
                              pg_code: ::std::os::raw::c_int,
                              resp: *mut ::std::os::raw::c_void,
                              mx_resp_len: ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_report_id_info(sg_fd: ::std::os::raw::c_int,
                                itype: ::std::os::raw::c_int,
                                resp: *mut ::std::os::raw::c_void,
                                max_resp_len: ::std::os::raw::c_int,
                                noisy: ::std::os::raw::c_int,
                                verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_report_tgt_prt_grp(sg_fd: ::std::os::raw::c_int,
                                    resp: *mut ::std::os::raw::c_void,
                                    mx_resp_len: ::std::os::raw::c_int,
                                    noisy: ::std::os::raw::c_int,
                                    verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_report_tgt_prt_grp2(sg_fd: ::std::os::raw::c_int,
                                     resp: *mut ::std::os::raw::c_void,
                                     mx_resp_len: ::std::os::raw::c_int,
                                     extended: ::std::os::raw::c_int,
                                     noisy: ::std::os::raw::c_int,
                                     verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_set_tgt_prt_grp(sg_fd: ::std::os::raw::c_int,
                                 paramp: *mut ::std::os::raw::c_void,
                                 param_len: ::std::os::raw::c_int,
                                 noisy: ::std::os::raw::c_int,
                                 verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_report_referrals(sg_fd: ::std::os::raw::c_int,
                                  start_llba: uint64_t,
                                  one_seg: ::std::os::raw::c_int,
                                  resp: *mut ::std::os::raw::c_void,
                                  mx_resp_len: ::std::os::raw::c_int,
                                  noisy: ::std::os::raw::c_int,
                                  verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_send_diag(sg_fd: ::std::os::raw::c_int,
                           sf_code: ::std::os::raw::c_int,
                           pf_bit: ::std::os::raw::c_int,
                           sf_bit: ::std::os::raw::c_int,
                           devofl_bit: ::std::os::raw::c_int,
                           unitofl_bit: ::std::os::raw::c_int,
                           long_duration: ::std::os::raw::c_int,
                           paramp: *mut ::std::os::raw::c_void,
                           param_len: ::std::os::raw::c_int,
                           noisy: ::std::os::raw::c_int,
                           verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_set_id_info(sg_fd: ::std::os::raw::c_int,
                             itype: ::std::os::raw::c_int,
                             paramp: *mut ::std::os::raw::c_void,
                             param_len: ::std::os::raw::c_int,
                             noisy: ::std::os::raw::c_int,
                             verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_unmap(sg_fd: ::std::os::raw::c_int,
                       group_num: ::std::os::raw::c_int,
                       timeout_secs: ::std::os::raw::c_int,
                       paramp: *mut ::std::os::raw::c_void,
                       param_len: ::std::os::raw::c_int,
                       noisy: ::std::os::raw::c_int,
                       verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_unmap_v2(sg_fd: ::std::os::raw::c_int,
                          anchor: ::std::os::raw::c_int,
                          group_num: ::std::os::raw::c_int,
                          timeout_secs: ::std::os::raw::c_int,
                          paramp: *mut ::std::os::raw::c_void,
                          param_len: ::std::os::raw::c_int,
                          noisy: ::std::os::raw::c_int,
                          verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_verify10(sg_fd: ::std::os::raw::c_int,
                          vrprotect: ::std::os::raw::c_int,
                          dpo: ::std::os::raw::c_int,
                          bytechk: ::std::os::raw::c_int,
                          lba: ::std::os::raw::c_uint,
                          veri_len: ::std::os::raw::c_int,
                          data_out: *mut ::std::os::raw::c_void,
                          data_out_len: ::std::os::raw::c_int,
                          infop: *mut ::std::os::raw::c_uint,
                          noisy: ::std::os::raw::c_int,
                          verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_verify16(sg_fd: ::std::os::raw::c_int,
                          vrprotect: ::std::os::raw::c_int,
                          dpo: ::std::os::raw::c_int,
                          bytechk: ::std::os::raw::c_int, llba: uint64_t,
                          veri_len: ::std::os::raw::c_int,
                          group_num: ::std::os::raw::c_int,
                          data_out: *mut ::std::os::raw::c_void,
                          data_out_len: ::std::os::raw::c_int,
                          infop: *mut uint64_t, noisy: ::std::os::raw::c_int,
                          verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_write_buffer(sg_fd: ::std::os::raw::c_int,
                              mode: ::std::os::raw::c_int,
                              buffer_id: ::std::os::raw::c_int,
                              buffer_offset: ::std::os::raw::c_int,
                              paramp: *mut ::std::os::raw::c_void,
                              param_len: ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_write_long10(sg_fd: ::std::os::raw::c_int,
                              cor_dis: ::std::os::raw::c_int,
                              wr_uncor: ::std::os::raw::c_int,
                              pblock: ::std::os::raw::c_int,
                              lba: ::std::os::raw::c_uint,
                              data_out: *mut ::std::os::raw::c_void,
                              xfer_len: ::std::os::raw::c_int,
                              offsetp: *mut ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_write_long16(sg_fd: ::std::os::raw::c_int,
                              cor_dis: ::std::os::raw::c_int,
                              wr_uncor: ::std::os::raw::c_int,
                              pblock: ::std::os::raw::c_int, llba: uint64_t,
                              data_out: *mut ::std::os::raw::c_void,
                              xfer_len: ::std::os::raw::c_int,
                              offsetp: *mut ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_receive_copy_results(sg_fd: ::std::os::raw::c_int,
                                      sa: ::std::os::raw::c_int,
                                      list_id: ::std::os::raw::c_int,
                                      resp: *mut ::std::os::raw::c_void,
                                      mx_resp_len: ::std::os::raw::c_int,
                                      noisy: ::std::os::raw::c_int,
                                      verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_extended_copy(sg_fd: ::std::os::raw::c_int,
                               paramp: *mut ::std::os::raw::c_void,
                               param_len: ::std::os::raw::c_int,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_3party_copy_out(sg_fd: ::std::os::raw::c_int,
                                 sa: ::std::os::raw::c_int,
                                 list_id: ::std::os::raw::c_uint,
                                 group_num: ::std::os::raw::c_int,
                                 timeout_secs: ::std::os::raw::c_int,
                                 paramp: *mut ::std::os::raw::c_void,
                                 param_len: ::std::os::raw::c_int,
                                 noisy: ::std::os::raw::c_int,
                                 verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_get_config(sg_fd: ::std::os::raw::c_int,
                            rt: ::std::os::raw::c_int,
                            starting: ::std::os::raw::c_int,
                            resp: *mut ::std::os::raw::c_void,
                            mx_resp_len: ::std::os::raw::c_int,
                            noisy: ::std::os::raw::c_int,
                            verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_get_performance(sg_fd: ::std::os::raw::c_int,
                                 data_type: ::std::os::raw::c_int,
                                 starting_lba: ::std::os::raw::c_uint,
                                 max_num_desc: ::std::os::raw::c_int,
                                 type_: ::std::os::raw::c_int,
                                 resp: *mut ::std::os::raw::c_void,
                                 mx_resp_len: ::std::os::raw::c_int,
                                 noisy: ::std::os::raw::c_int,
                                 verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_set_cd_speed(sg_fd: ::std::os::raw::c_int,
                              rot_control: ::std::os::raw::c_int,
                              drv_read_speed: ::std::os::raw::c_int,
                              drv_write_speed: ::std::os::raw::c_int,
                              noisy: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn sg_ll_set_streaming(sg_fd: ::std::os::raw::c_int,
                               type_: ::std::os::raw::c_int,
                               paramp: *mut ::std::os::raw::c_void,
                               param_len: ::std::os::raw::c_int,
                               noisy: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
}
