/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub enum sg_pt_base { }
extern "C" {
    pub fn scsi_pt_version() -> *const ::std::os::raw::c_char;
    pub fn scsi_pt_open_device(device_name: *const ::std::os::raw::c_char,
                               read_only: ::std::os::raw::c_int,
                               verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn scsi_pt_open_flags(device_name: *const ::std::os::raw::c_char,
                              flags: ::std::os::raw::c_int,
                              verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn scsi_pt_close_device(device_fd: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn construct_scsi_pt_obj() -> *mut sg_pt_base;
    pub fn clear_scsi_pt_obj(objp: *mut sg_pt_base);
    pub fn set_scsi_pt_cdb(objp: *mut sg_pt_base,
                           cdb: *const ::std::os::raw::c_uchar,
                           cdb_len: ::std::os::raw::c_int);
    pub fn set_scsi_pt_sense(objp: *mut sg_pt_base,
                             sense: *mut ::std::os::raw::c_uchar,
                             max_sense_len: ::std::os::raw::c_int);
    pub fn set_scsi_pt_data_in(objp: *mut sg_pt_base,
                               dxferp: *mut ::std::os::raw::c_uchar,
                               dxfer_len: ::std::os::raw::c_int);
    pub fn set_scsi_pt_data_out(objp: *mut sg_pt_base,
                                dxferp: *const ::std::os::raw::c_uchar,
                                dxfer_len: ::std::os::raw::c_int);
    pub fn set_scsi_pt_packet_id(objp: *mut sg_pt_base,
                                 pack_id: ::std::os::raw::c_int);
    pub fn set_scsi_pt_tag(objp: *mut sg_pt_base, tag: uint64_t);
    pub fn set_scsi_pt_task_management(objp: *mut sg_pt_base,
                                       tmf_code: ::std::os::raw::c_int);
    pub fn set_scsi_pt_task_attr(objp: *mut sg_pt_base,
                                 attribute: ::std::os::raw::c_int,
                                 priority: ::std::os::raw::c_int);
    pub fn set_scsi_pt_flags(objp: *mut sg_pt_base,
                             flags: ::std::os::raw::c_int);
    pub fn do_scsi_pt(objp: *mut sg_pt_base, fd: ::std::os::raw::c_int,
                      timeout_secs: ::std::os::raw::c_int,
                      verbose: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_result_category(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_resid(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_status_response(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_sense_len(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_os_err(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_os_err_str(objp: *const sg_pt_base,
                                  max_b_len: ::std::os::raw::c_int,
                                  b: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn get_scsi_pt_transport_err(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn get_scsi_pt_transport_err_str(objp: *const sg_pt_base,
                                         max_b_len: ::std::os::raw::c_int,
                                         b: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn get_scsi_pt_duration_ms(objp: *const sg_pt_base)
     -> ::std::os::raw::c_int;
    pub fn destruct_scsi_pt_obj(objp: *mut sg_pt_base);
}
